import * as cdk from "aws-cdk-lib";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import * as ssm from "aws-cdk-lib/aws-ssm";
import * as logs from "aws-cdk-lib/aws-logs";
import { Construct } from "constructs";
import { SystemConfig } from "./types";
import { NagSuppressions } from "cdk-nag";

const lambdaArchitecture = lambda.Architecture.X86_64;
process.env.DOCKER_DEFAULT_PLATFORM = lambdaArchitecture.dockerPlatform;

export interface SharedProps {
  readonly config: SystemConfig;
}

export class Shared extends Construct {
  readonly vpc: ec2.Vpc;
  readonly configParameter: ssm.StringParameter;
  readonly xOriginVerifySecret: secretsmanager.Secret;
  readonly apiKeysSecret: secretsmanager.Secret;
  readonly s3vpcEndpoint: ec2.InterfaceVpcEndpoint;

  constructor(scope: Construct, id: string, props: SharedProps) {
    super(scope, id);

    let vpc: ec2.Vpc;
    if (!props.config.vpc?.vpcId) {
      vpc = new ec2.Vpc(this, "VPC", {
        natGateways: 1,
        restrictDefaultSecurityGroup: false,
        subnetConfiguration: [
          {
            name: "public",
            subnetType: ec2.SubnetType.PUBLIC,
          },
          {
            name: "private",
            subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
          },
          {
            name: "isolated",
            subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
          },
        ],
      });
      const logGroup = new logs.LogGroup(this, "FLowLogsLogGroup", {
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      });
      new ec2.FlowLog(this, "FlowLog", {
        resourceType: ec2.FlowLogResourceType.fromVpc(vpc),
        destination: ec2.FlowLogDestination.toCloudWatchLogs(logGroup),
      });
    } else {
      vpc = ec2.Vpc.fromLookup(this, "VPC", {
        vpcId: props.config.vpc.vpcId,
      }) as ec2.Vpc;
    }

    if (
      typeof props.config.vpc?.createVpcEndpoints === "undefined" ||
      props.config.vpc?.createVpcEndpoints === true
    ) {
      // Create a VPC endpoint for S3.
      const s3GatewayEndpoint = vpc.addGatewayEndpoint("S3GatewayEndpoint", {
        service: ec2.GatewayVpcEndpointAwsService.S3,
      });

      const s3vpcEndpoint = vpc.addInterfaceEndpoint("S3InterfaceEndpoint", {
        service: ec2.InterfaceVpcEndpointAwsService.S3,
        privateDnsEnabled: true,
        open: true,
      });

      this.s3vpcEndpoint = s3vpcEndpoint;

      s3vpcEndpoint.node.addDependency(s3GatewayEndpoint);

      // Create a VPC endpoint for DynamoDB.
      vpc.addGatewayEndpoint("DynamoDBEndpoint", {
        service: ec2.GatewayVpcEndpointAwsService.DYNAMODB,
      });

      // Create VPC Endpoint for Secrets Manager
      vpc.addInterfaceEndpoint("SecretsManagerEndpoint", {
        service: ec2.InterfaceVpcEndpointAwsService.SECRETS_MANAGER,
        open: true,
      });

      // Create VPC Endpoint for SageMaker Runtime
      vpc.addInterfaceEndpoint("SageMakerRuntimeEndpoint", {
        service: ec2.InterfaceVpcEndpointAwsService.SAGEMAKER_RUNTIME,
        open: true,
      });
    }

    const configParameter = new ssm.StringParameter(this, "Config", {
      stringValue: JSON.stringify(props.config),
    });

    const xOriginVerifySecret = new secretsmanager.Secret(
      this,
      "X-Origin-Verify-Secret",
      {
        removalPolicy: cdk.RemovalPolicy.DESTROY,
        generateSecretString: {
          excludePunctuation: true,
          generateStringKey: "headerValue",
          secretStringTemplate: "{}",
        },
      }
    );

    const apiKeysSecret = new secretsmanager.Secret(this, "ApiKeysSecret", {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      secretObjectValue: {},
    });

    this.vpc = vpc;
    this.configParameter = configParameter;
    this.xOriginVerifySecret = xOriginVerifySecret;
    this.apiKeysSecret = apiKeysSecret;

    new cdk.CfnOutput(this, "ApiKeysSecretName", {
      value: apiKeysSecret.secretName,
    });

    /**
     * CDK NAG suppression
     */
    NagSuppressions.addResourceSuppressions(xOriginVerifySecret, [
      { id: "AwsSolutions-SMG4", reason: "Secret is generated by CDK." },
    ]);
    NagSuppressions.addResourceSuppressions(apiKeysSecret, [
      { id: "AwsSolutions-SMG4", reason: "Secret value is blank." },
    ]);
  }
}
