"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Shared = void 0;
const cdk = require("aws-cdk-lib");
const ec2 = require("aws-cdk-lib/aws-ec2");
const lambda = require("aws-cdk-lib/aws-lambda");
const secretsmanager = require("aws-cdk-lib/aws-secretsmanager");
const ssm = require("aws-cdk-lib/aws-ssm");
const logs = require("aws-cdk-lib/aws-logs");
const constructs_1 = require("constructs");
const cdk_nag_1 = require("cdk-nag");
const lambdaArchitecture = lambda.Architecture.X86_64;
process.env.DOCKER_DEFAULT_PLATFORM = lambdaArchitecture.dockerPlatform;
class Shared extends constructs_1.Construct {
    constructor(scope, id, props) {
        super(scope, id);
        let vpc;
        if (!props.config.vpc?.vpcId) {
            vpc = new ec2.Vpc(this, "VPC", {
                natGateways: 1,
                restrictDefaultSecurityGroup: false,
                subnetConfiguration: [
                    {
                        name: "public",
                        subnetType: ec2.SubnetType.PUBLIC,
                    },
                    {
                        name: "private",
                        subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
                    },
                    {
                        name: "isolated",
                        subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
                    },
                ],
            });
            const logGroup = new logs.LogGroup(this, "FLowLogsLogGroup", {
                removalPolicy: cdk.RemovalPolicy.DESTROY,
            });
            new ec2.FlowLog(this, "FlowLog", {
                resourceType: ec2.FlowLogResourceType.fromVpc(vpc),
                destination: ec2.FlowLogDestination.toCloudWatchLogs(logGroup),
            });
        }
        else {
            vpc = ec2.Vpc.fromLookup(this, "VPC", {
                vpcId: props.config.vpc.vpcId,
            });
        }
        if (typeof props.config.vpc?.createVpcEndpoints === "undefined" ||
            props.config.vpc?.createVpcEndpoints === true) {
            // Create a VPC endpoint for S3.
            const s3GatewayEndpoint = vpc.addGatewayEndpoint("S3GatewayEndpoint", {
                service: ec2.GatewayVpcEndpointAwsService.S3,
            });
            const s3vpcEndpoint = vpc.addInterfaceEndpoint("S3InterfaceEndpoint", {
                service: ec2.InterfaceVpcEndpointAwsService.S3,
                privateDnsEnabled: true,
                open: true,
            });
            this.s3vpcEndpoint = s3vpcEndpoint;
            s3vpcEndpoint.node.addDependency(s3GatewayEndpoint);
            // Create a VPC endpoint for DynamoDB.
            vpc.addGatewayEndpoint("DynamoDBEndpoint", {
                service: ec2.GatewayVpcEndpointAwsService.DYNAMODB,
            });
            // Create VPC Endpoint for Secrets Manager
            vpc.addInterfaceEndpoint("SecretsManagerEndpoint", {
                service: ec2.InterfaceVpcEndpointAwsService.SECRETS_MANAGER,
                open: true,
            });
            // Create VPC Endpoint for SageMaker Runtime
            vpc.addInterfaceEndpoint("SageMakerRuntimeEndpoint", {
                service: ec2.InterfaceVpcEndpointAwsService.SAGEMAKER_RUNTIME,
                open: true,
            });
        }
        const configParameter = new ssm.StringParameter(this, "Config", {
            stringValue: JSON.stringify(props.config),
        });
        const xOriginVerifySecret = new secretsmanager.Secret(this, "X-Origin-Verify-Secret", {
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            generateSecretString: {
                excludePunctuation: true,
                generateStringKey: "headerValue",
                secretStringTemplate: "{}",
            },
        });
        const apiKeysSecret = new secretsmanager.Secret(this, "ApiKeysSecret", {
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            secretObjectValue: {},
        });
        this.vpc = vpc;
        this.configParameter = configParameter;
        this.xOriginVerifySecret = xOriginVerifySecret;
        this.apiKeysSecret = apiKeysSecret;
        new cdk.CfnOutput(this, "ApiKeysSecretName", {
            value: apiKeysSecret.secretName,
        });
        /**
         * CDK NAG suppression
         */
        cdk_nag_1.NagSuppressions.addResourceSuppressions(xOriginVerifySecret, [
            { id: "AwsSolutions-SMG4", reason: "Secret is generated by CDK." },
        ]);
        cdk_nag_1.NagSuppressions.addResourceSuppressions(apiKeysSecret, [
            { id: "AwsSolutions-SMG4", reason: "Secret value is blank." },
        ]);
    }
}
exports.Shared = Shared;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJpbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7QUFBQSxtQ0FBbUM7QUFDbkMsMkNBQTJDO0FBQzNDLGlEQUFpRDtBQUNqRCxpRUFBaUU7QUFDakUsMkNBQTJDO0FBQzNDLDZDQUE2QztBQUM3QywyQ0FBdUM7QUFFdkMscUNBQTBDO0FBRTFDLE1BQU0sa0JBQWtCLEdBQUcsTUFBTSxDQUFDLFlBQVksQ0FBQyxNQUFNLENBQUM7QUFDdEQsT0FBTyxDQUFDLEdBQUcsQ0FBQyx1QkFBdUIsR0FBRyxrQkFBa0IsQ0FBQyxjQUFjLENBQUM7QUFNeEUsTUFBYSxNQUFPLFNBQVEsc0JBQVM7SUFPbkMsWUFBWSxLQUFnQixFQUFFLEVBQVUsRUFBRSxLQUFrQjtRQUMxRCxLQUFLLENBQUMsS0FBSyxFQUFFLEVBQUUsQ0FBQyxDQUFDO1FBRWpCLElBQUksR0FBWSxDQUFDO1FBQ2pCLElBQUksQ0FBQyxLQUFLLENBQUMsTUFBTSxDQUFDLEdBQUcsRUFBRSxLQUFLLEVBQUUsQ0FBQztZQUM3QixHQUFHLEdBQUcsSUFBSSxHQUFHLENBQUMsR0FBRyxDQUFDLElBQUksRUFBRSxLQUFLLEVBQUU7Z0JBQzdCLFdBQVcsRUFBRSxDQUFDO2dCQUNkLDRCQUE0QixFQUFFLEtBQUs7Z0JBQ25DLG1CQUFtQixFQUFFO29CQUNuQjt3QkFDRSxJQUFJLEVBQUUsUUFBUTt3QkFDZCxVQUFVLEVBQUUsR0FBRyxDQUFDLFVBQVUsQ0FBQyxNQUFNO3FCQUNsQztvQkFDRDt3QkFDRSxJQUFJLEVBQUUsU0FBUzt3QkFDZixVQUFVLEVBQUUsR0FBRyxDQUFDLFVBQVUsQ0FBQyxtQkFBbUI7cUJBQy9DO29CQUNEO3dCQUNFLElBQUksRUFBRSxVQUFVO3dCQUNoQixVQUFVLEVBQUUsR0FBRyxDQUFDLFVBQVUsQ0FBQyxnQkFBZ0I7cUJBQzVDO2lCQUNGO2FBQ0YsQ0FBQyxDQUFDO1lBQ0gsTUFBTSxRQUFRLEdBQUcsSUFBSSxJQUFJLENBQUMsUUFBUSxDQUFDLElBQUksRUFBRSxrQkFBa0IsRUFBRTtnQkFDM0QsYUFBYSxFQUFFLEdBQUcsQ0FBQyxhQUFhLENBQUMsT0FBTzthQUN6QyxDQUFDLENBQUM7WUFDSCxJQUFJLEdBQUcsQ0FBQyxPQUFPLENBQUMsSUFBSSxFQUFFLFNBQVMsRUFBRTtnQkFDL0IsWUFBWSxFQUFFLEdBQUcsQ0FBQyxtQkFBbUIsQ0FBQyxPQUFPLENBQUMsR0FBRyxDQUFDO2dCQUNsRCxXQUFXLEVBQUUsR0FBRyxDQUFDLGtCQUFrQixDQUFDLGdCQUFnQixDQUFDLFFBQVEsQ0FBQzthQUMvRCxDQUFDLENBQUM7UUFDTCxDQUFDO2FBQU0sQ0FBQztZQUNOLEdBQUcsR0FBRyxHQUFHLENBQUMsR0FBRyxDQUFDLFVBQVUsQ0FBQyxJQUFJLEVBQUUsS0FBSyxFQUFFO2dCQUNwQyxLQUFLLEVBQUUsS0FBSyxDQUFDLE1BQU0sQ0FBQyxHQUFHLENBQUMsS0FBSzthQUM5QixDQUFZLENBQUM7UUFDaEIsQ0FBQztRQUVELElBQ0UsT0FBTyxLQUFLLENBQUMsTUFBTSxDQUFDLEdBQUcsRUFBRSxrQkFBa0IsS0FBSyxXQUFXO1lBQzNELEtBQUssQ0FBQyxNQUFNLENBQUMsR0FBRyxFQUFFLGtCQUFrQixLQUFLLElBQUksRUFDN0MsQ0FBQztZQUNELGdDQUFnQztZQUNoQyxNQUFNLGlCQUFpQixHQUFHLEdBQUcsQ0FBQyxrQkFBa0IsQ0FBQyxtQkFBbUIsRUFBRTtnQkFDcEUsT0FBTyxFQUFFLEdBQUcsQ0FBQyw0QkFBNEIsQ0FBQyxFQUFFO2FBQzdDLENBQUMsQ0FBQztZQUVILE1BQU0sYUFBYSxHQUFHLEdBQUcsQ0FBQyxvQkFBb0IsQ0FBQyxxQkFBcUIsRUFBRTtnQkFDcEUsT0FBTyxFQUFFLEdBQUcsQ0FBQyw4QkFBOEIsQ0FBQyxFQUFFO2dCQUM5QyxpQkFBaUIsRUFBRSxJQUFJO2dCQUN2QixJQUFJLEVBQUUsSUFBSTthQUNYLENBQUMsQ0FBQztZQUVILElBQUksQ0FBQyxhQUFhLEdBQUcsYUFBYSxDQUFDO1lBRW5DLGFBQWEsQ0FBQyxJQUFJLENBQUMsYUFBYSxDQUFDLGlCQUFpQixDQUFDLENBQUM7WUFFcEQsc0NBQXNDO1lBQ3RDLEdBQUcsQ0FBQyxrQkFBa0IsQ0FBQyxrQkFBa0IsRUFBRTtnQkFDekMsT0FBTyxFQUFFLEdBQUcsQ0FBQyw0QkFBNEIsQ0FBQyxRQUFRO2FBQ25ELENBQUMsQ0FBQztZQUVILDBDQUEwQztZQUMxQyxHQUFHLENBQUMsb0JBQW9CLENBQUMsd0JBQXdCLEVBQUU7Z0JBQ2pELE9BQU8sRUFBRSxHQUFHLENBQUMsOEJBQThCLENBQUMsZUFBZTtnQkFDM0QsSUFBSSxFQUFFLElBQUk7YUFDWCxDQUFDLENBQUM7WUFFSCw0Q0FBNEM7WUFDNUMsR0FBRyxDQUFDLG9CQUFvQixDQUFDLDBCQUEwQixFQUFFO2dCQUNuRCxPQUFPLEVBQUUsR0FBRyxDQUFDLDhCQUE4QixDQUFDLGlCQUFpQjtnQkFDN0QsSUFBSSxFQUFFLElBQUk7YUFDWCxDQUFDLENBQUM7UUFDTCxDQUFDO1FBRUQsTUFBTSxlQUFlLEdBQUcsSUFBSSxHQUFHLENBQUMsZUFBZSxDQUFDLElBQUksRUFBRSxRQUFRLEVBQUU7WUFDOUQsV0FBVyxFQUFFLElBQUksQ0FBQyxTQUFTLENBQUMsS0FBSyxDQUFDLE1BQU0sQ0FBQztTQUMxQyxDQUFDLENBQUM7UUFFSCxNQUFNLG1CQUFtQixHQUFHLElBQUksY0FBYyxDQUFDLE1BQU0sQ0FDbkQsSUFBSSxFQUNKLHdCQUF3QixFQUN4QjtZQUNFLGFBQWEsRUFBRSxHQUFHLENBQUMsYUFBYSxDQUFDLE9BQU87WUFDeEMsb0JBQW9CLEVBQUU7Z0JBQ3BCLGtCQUFrQixFQUFFLElBQUk7Z0JBQ3hCLGlCQUFpQixFQUFFLGFBQWE7Z0JBQ2hDLG9CQUFvQixFQUFFLElBQUk7YUFDM0I7U0FDRixDQUNGLENBQUM7UUFFRixNQUFNLGFBQWEsR0FBRyxJQUFJLGNBQWMsQ0FBQyxNQUFNLENBQUMsSUFBSSxFQUFFLGVBQWUsRUFBRTtZQUNyRSxhQUFhLEVBQUUsR0FBRyxDQUFDLGFBQWEsQ0FBQyxPQUFPO1lBQ3hDLGlCQUFpQixFQUFFLEVBQUU7U0FDdEIsQ0FBQyxDQUFDO1FBRUgsSUFBSSxDQUFDLEdBQUcsR0FBRyxHQUFHLENBQUM7UUFDZixJQUFJLENBQUMsZUFBZSxHQUFHLGVBQWUsQ0FBQztRQUN2QyxJQUFJLENBQUMsbUJBQW1CLEdBQUcsbUJBQW1CLENBQUM7UUFDL0MsSUFBSSxDQUFDLGFBQWEsR0FBRyxhQUFhLENBQUM7UUFFbkMsSUFBSSxHQUFHLENBQUMsU0FBUyxDQUFDLElBQUksRUFBRSxtQkFBbUIsRUFBRTtZQUMzQyxLQUFLLEVBQUUsYUFBYSxDQUFDLFVBQVU7U0FDaEMsQ0FBQyxDQUFDO1FBRUg7O1dBRUc7UUFDSCx5QkFBZSxDQUFDLHVCQUF1QixDQUFDLG1CQUFtQixFQUFFO1lBQzNELEVBQUUsRUFBRSxFQUFFLG1CQUFtQixFQUFFLE1BQU0sRUFBRSw2QkFBNkIsRUFBRTtTQUNuRSxDQUFDLENBQUM7UUFDSCx5QkFBZSxDQUFDLHVCQUF1QixDQUFDLGFBQWEsRUFBRTtZQUNyRCxFQUFFLEVBQUUsRUFBRSxtQkFBbUIsRUFBRSxNQUFNLEVBQUUsd0JBQXdCLEVBQUU7U0FDOUQsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztDQUNGO0FBekhELHdCQXlIQyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCAqIGFzIGNkayBmcm9tIFwiYXdzLWNkay1saWJcIjtcbmltcG9ydCAqIGFzIGVjMiBmcm9tIFwiYXdzLWNkay1saWIvYXdzLWVjMlwiO1xuaW1wb3J0ICogYXMgbGFtYmRhIGZyb20gXCJhd3MtY2RrLWxpYi9hd3MtbGFtYmRhXCI7XG5pbXBvcnQgKiBhcyBzZWNyZXRzbWFuYWdlciBmcm9tIFwiYXdzLWNkay1saWIvYXdzLXNlY3JldHNtYW5hZ2VyXCI7XG5pbXBvcnQgKiBhcyBzc20gZnJvbSBcImF3cy1jZGstbGliL2F3cy1zc21cIjtcbmltcG9ydCAqIGFzIGxvZ3MgZnJvbSBcImF3cy1jZGstbGliL2F3cy1sb2dzXCI7XG5pbXBvcnQgeyBDb25zdHJ1Y3QgfSBmcm9tIFwiY29uc3RydWN0c1wiO1xuaW1wb3J0IHsgU3lzdGVtQ29uZmlnIH0gZnJvbSBcIi4vdHlwZXNcIjtcbmltcG9ydCB7IE5hZ1N1cHByZXNzaW9ucyB9IGZyb20gXCJjZGstbmFnXCI7XG5cbmNvbnN0IGxhbWJkYUFyY2hpdGVjdHVyZSA9IGxhbWJkYS5BcmNoaXRlY3R1cmUuWDg2XzY0O1xucHJvY2Vzcy5lbnYuRE9DS0VSX0RFRkFVTFRfUExBVEZPUk0gPSBsYW1iZGFBcmNoaXRlY3R1cmUuZG9ja2VyUGxhdGZvcm07XG5cbmV4cG9ydCBpbnRlcmZhY2UgU2hhcmVkUHJvcHMge1xuICByZWFkb25seSBjb25maWc6IFN5c3RlbUNvbmZpZztcbn1cblxuZXhwb3J0IGNsYXNzIFNoYXJlZCBleHRlbmRzIENvbnN0cnVjdCB7XG4gIHJlYWRvbmx5IHZwYzogZWMyLlZwYztcbiAgcmVhZG9ubHkgY29uZmlnUGFyYW1ldGVyOiBzc20uU3RyaW5nUGFyYW1ldGVyO1xuICByZWFkb25seSB4T3JpZ2luVmVyaWZ5U2VjcmV0OiBzZWNyZXRzbWFuYWdlci5TZWNyZXQ7XG4gIHJlYWRvbmx5IGFwaUtleXNTZWNyZXQ6IHNlY3JldHNtYW5hZ2VyLlNlY3JldDtcbiAgcmVhZG9ubHkgczN2cGNFbmRwb2ludDogZWMyLkludGVyZmFjZVZwY0VuZHBvaW50O1xuXG4gIGNvbnN0cnVjdG9yKHNjb3BlOiBDb25zdHJ1Y3QsIGlkOiBzdHJpbmcsIHByb3BzOiBTaGFyZWRQcm9wcykge1xuICAgIHN1cGVyKHNjb3BlLCBpZCk7XG5cbiAgICBsZXQgdnBjOiBlYzIuVnBjO1xuICAgIGlmICghcHJvcHMuY29uZmlnLnZwYz8udnBjSWQpIHtcbiAgICAgIHZwYyA9IG5ldyBlYzIuVnBjKHRoaXMsIFwiVlBDXCIsIHtcbiAgICAgICAgbmF0R2F0ZXdheXM6IDEsXG4gICAgICAgIHJlc3RyaWN0RGVmYXVsdFNlY3VyaXR5R3JvdXA6IGZhbHNlLFxuICAgICAgICBzdWJuZXRDb25maWd1cmF0aW9uOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogXCJwdWJsaWNcIixcbiAgICAgICAgICAgIHN1Ym5ldFR5cGU6IGVjMi5TdWJuZXRUeXBlLlBVQkxJQyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIG5hbWU6IFwicHJpdmF0ZVwiLFxuICAgICAgICAgICAgc3VibmV0VHlwZTogZWMyLlN1Ym5ldFR5cGUuUFJJVkFURV9XSVRIX0VHUkVTUyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIG5hbWU6IFwiaXNvbGF0ZWRcIixcbiAgICAgICAgICAgIHN1Ym5ldFR5cGU6IGVjMi5TdWJuZXRUeXBlLlBSSVZBVEVfSVNPTEFURUQsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0pO1xuICAgICAgY29uc3QgbG9nR3JvdXAgPSBuZXcgbG9ncy5Mb2dHcm91cCh0aGlzLCBcIkZMb3dMb2dzTG9nR3JvdXBcIiwge1xuICAgICAgICByZW1vdmFsUG9saWN5OiBjZGsuUmVtb3ZhbFBvbGljeS5ERVNUUk9ZLFxuICAgICAgfSk7XG4gICAgICBuZXcgZWMyLkZsb3dMb2codGhpcywgXCJGbG93TG9nXCIsIHtcbiAgICAgICAgcmVzb3VyY2VUeXBlOiBlYzIuRmxvd0xvZ1Jlc291cmNlVHlwZS5mcm9tVnBjKHZwYyksXG4gICAgICAgIGRlc3RpbmF0aW9uOiBlYzIuRmxvd0xvZ0Rlc3RpbmF0aW9uLnRvQ2xvdWRXYXRjaExvZ3MobG9nR3JvdXApLFxuICAgICAgfSk7XG4gICAgfSBlbHNlIHtcbiAgICAgIHZwYyA9IGVjMi5WcGMuZnJvbUxvb2t1cCh0aGlzLCBcIlZQQ1wiLCB7XG4gICAgICAgIHZwY0lkOiBwcm9wcy5jb25maWcudnBjLnZwY0lkLFxuICAgICAgfSkgYXMgZWMyLlZwYztcbiAgICB9XG5cbiAgICBpZiAoXG4gICAgICB0eXBlb2YgcHJvcHMuY29uZmlnLnZwYz8uY3JlYXRlVnBjRW5kcG9pbnRzID09PSBcInVuZGVmaW5lZFwiIHx8XG4gICAgICBwcm9wcy5jb25maWcudnBjPy5jcmVhdGVWcGNFbmRwb2ludHMgPT09IHRydWVcbiAgICApIHtcbiAgICAgIC8vIENyZWF0ZSBhIFZQQyBlbmRwb2ludCBmb3IgUzMuXG4gICAgICBjb25zdCBzM0dhdGV3YXlFbmRwb2ludCA9IHZwYy5hZGRHYXRld2F5RW5kcG9pbnQoXCJTM0dhdGV3YXlFbmRwb2ludFwiLCB7XG4gICAgICAgIHNlcnZpY2U6IGVjMi5HYXRld2F5VnBjRW5kcG9pbnRBd3NTZXJ2aWNlLlMzLFxuICAgICAgfSk7XG5cbiAgICAgIGNvbnN0IHMzdnBjRW5kcG9pbnQgPSB2cGMuYWRkSW50ZXJmYWNlRW5kcG9pbnQoXCJTM0ludGVyZmFjZUVuZHBvaW50XCIsIHtcbiAgICAgICAgc2VydmljZTogZWMyLkludGVyZmFjZVZwY0VuZHBvaW50QXdzU2VydmljZS5TMyxcbiAgICAgICAgcHJpdmF0ZURuc0VuYWJsZWQ6IHRydWUsXG4gICAgICAgIG9wZW46IHRydWUsXG4gICAgICB9KTtcblxuICAgICAgdGhpcy5zM3ZwY0VuZHBvaW50ID0gczN2cGNFbmRwb2ludDtcblxuICAgICAgczN2cGNFbmRwb2ludC5ub2RlLmFkZERlcGVuZGVuY3koczNHYXRld2F5RW5kcG9pbnQpO1xuXG4gICAgICAvLyBDcmVhdGUgYSBWUEMgZW5kcG9pbnQgZm9yIER5bmFtb0RCLlxuICAgICAgdnBjLmFkZEdhdGV3YXlFbmRwb2ludChcIkR5bmFtb0RCRW5kcG9pbnRcIiwge1xuICAgICAgICBzZXJ2aWNlOiBlYzIuR2F0ZXdheVZwY0VuZHBvaW50QXdzU2VydmljZS5EWU5BTU9EQixcbiAgICAgIH0pO1xuXG4gICAgICAvLyBDcmVhdGUgVlBDIEVuZHBvaW50IGZvciBTZWNyZXRzIE1hbmFnZXJcbiAgICAgIHZwYy5hZGRJbnRlcmZhY2VFbmRwb2ludChcIlNlY3JldHNNYW5hZ2VyRW5kcG9pbnRcIiwge1xuICAgICAgICBzZXJ2aWNlOiBlYzIuSW50ZXJmYWNlVnBjRW5kcG9pbnRBd3NTZXJ2aWNlLlNFQ1JFVFNfTUFOQUdFUixcbiAgICAgICAgb3BlbjogdHJ1ZSxcbiAgICAgIH0pO1xuXG4gICAgICAvLyBDcmVhdGUgVlBDIEVuZHBvaW50IGZvciBTYWdlTWFrZXIgUnVudGltZVxuICAgICAgdnBjLmFkZEludGVyZmFjZUVuZHBvaW50KFwiU2FnZU1ha2VyUnVudGltZUVuZHBvaW50XCIsIHtcbiAgICAgICAgc2VydmljZTogZWMyLkludGVyZmFjZVZwY0VuZHBvaW50QXdzU2VydmljZS5TQUdFTUFLRVJfUlVOVElNRSxcbiAgICAgICAgb3BlbjogdHJ1ZSxcbiAgICAgIH0pO1xuICAgIH1cblxuICAgIGNvbnN0IGNvbmZpZ1BhcmFtZXRlciA9IG5ldyBzc20uU3RyaW5nUGFyYW1ldGVyKHRoaXMsIFwiQ29uZmlnXCIsIHtcbiAgICAgIHN0cmluZ1ZhbHVlOiBKU09OLnN0cmluZ2lmeShwcm9wcy5jb25maWcpLFxuICAgIH0pO1xuXG4gICAgY29uc3QgeE9yaWdpblZlcmlmeVNlY3JldCA9IG5ldyBzZWNyZXRzbWFuYWdlci5TZWNyZXQoXG4gICAgICB0aGlzLFxuICAgICAgXCJYLU9yaWdpbi1WZXJpZnktU2VjcmV0XCIsXG4gICAgICB7XG4gICAgICAgIHJlbW92YWxQb2xpY3k6IGNkay5SZW1vdmFsUG9saWN5LkRFU1RST1ksXG4gICAgICAgIGdlbmVyYXRlU2VjcmV0U3RyaW5nOiB7XG4gICAgICAgICAgZXhjbHVkZVB1bmN0dWF0aW9uOiB0cnVlLFxuICAgICAgICAgIGdlbmVyYXRlU3RyaW5nS2V5OiBcImhlYWRlclZhbHVlXCIsXG4gICAgICAgICAgc2VjcmV0U3RyaW5nVGVtcGxhdGU6IFwie31cIixcbiAgICAgICAgfSxcbiAgICAgIH1cbiAgICApO1xuXG4gICAgY29uc3QgYXBpS2V5c1NlY3JldCA9IG5ldyBzZWNyZXRzbWFuYWdlci5TZWNyZXQodGhpcywgXCJBcGlLZXlzU2VjcmV0XCIsIHtcbiAgICAgIHJlbW92YWxQb2xpY3k6IGNkay5SZW1vdmFsUG9saWN5LkRFU1RST1ksXG4gICAgICBzZWNyZXRPYmplY3RWYWx1ZToge30sXG4gICAgfSk7XG5cbiAgICB0aGlzLnZwYyA9IHZwYztcbiAgICB0aGlzLmNvbmZpZ1BhcmFtZXRlciA9IGNvbmZpZ1BhcmFtZXRlcjtcbiAgICB0aGlzLnhPcmlnaW5WZXJpZnlTZWNyZXQgPSB4T3JpZ2luVmVyaWZ5U2VjcmV0O1xuICAgIHRoaXMuYXBpS2V5c1NlY3JldCA9IGFwaUtleXNTZWNyZXQ7XG5cbiAgICBuZXcgY2RrLkNmbk91dHB1dCh0aGlzLCBcIkFwaUtleXNTZWNyZXROYW1lXCIsIHtcbiAgICAgIHZhbHVlOiBhcGlLZXlzU2VjcmV0LnNlY3JldE5hbWUsXG4gICAgfSk7XG5cbiAgICAvKipcbiAgICAgKiBDREsgTkFHIHN1cHByZXNzaW9uXG4gICAgICovXG4gICAgTmFnU3VwcHJlc3Npb25zLmFkZFJlc291cmNlU3VwcHJlc3Npb25zKHhPcmlnaW5WZXJpZnlTZWNyZXQsIFtcbiAgICAgIHsgaWQ6IFwiQXdzU29sdXRpb25zLVNNRzRcIiwgcmVhc29uOiBcIlNlY3JldCBpcyBnZW5lcmF0ZWQgYnkgQ0RLLlwiIH0sXG4gICAgXSk7XG4gICAgTmFnU3VwcHJlc3Npb25zLmFkZFJlc291cmNlU3VwcHJlc3Npb25zKGFwaUtleXNTZWNyZXQsIFtcbiAgICAgIHsgaWQ6IFwiQXdzU29sdXRpb25zLVNNRzRcIiwgcmVhc29uOiBcIlNlY3JldCB2YWx1ZSBpcyBibGFuay5cIiB9LFxuICAgIF0pO1xuICB9XG59XG4iXX0=